spring.application.name=Proyecto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://127.0.0.1:3308/proyectodb?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=borealos
spring.datasource.password=borealos18
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Esto ayudará a que Hibernate cree las tablas automáticamente sin errores
spring.h2.console.enabled=true

org.gradle.jvmargs=-Djunit.jupiter.execution.parallel.enabled=false